<table id="playlist">
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
    <tr><td><a href="Odezenne-TuPuDuCu.mp3">Odezenne-TuPuDuCu</a></td></tr>
    <tr><td><a href="T'es triste.mp3">T'es triste</a></td></tr>
    <tr><td><a href="Whip.mp3">Whip</a></td></tr>
</table>